"""
AgentOS Database Module

Handles SQLite connection, migrations, and base queries.
All operations are async using aiosqlite.
"""

import aiosqlite
import json
import os
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any

# Store DB in a consistent location.
# Priority: AGENTOS_DB_PATH env var > ~/.agentos/agentos.db
# Note: When installed via pip, the DB persists in the user's home directory.
# When running from source, set AGENTOS_DB_PATH to use a project-local DB.
if os.environ.get("AGENTOS_DB_PATH"):
    DB_PATH = os.environ["AGENTOS_DB_PATH"]
else:
    _default_db_dir = os.path.join(os.path.expanduser("~"), ".agentos")
    os.makedirs(_default_db_dir, exist_ok=True)
    DB_PATH = os.path.join(_default_db_dir, "agentos.db")

# SQL Schema
SCHEMA_SQL = """
-- Memories table (structured data)
CREATE TABLE IF NOT EXISTS memories (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    content TEXT NOT NULL,
    summary TEXT,
    importance REAL DEFAULT 0.5,
    memory_type TEXT DEFAULT 'episodic',
    tags TEXT DEFAULT '[]',
    created_at TEXT NOT NULL,
    last_accessed TEXT,
    access_count INTEGER DEFAULT 0,
    decay_score REAL DEFAULT 1.0
);
CREATE INDEX IF NOT EXISTS idx_memories_agent ON memories(agent_id);
CREATE INDEX IF NOT EXISTS idx_memories_type ON memories(memory_type);

-- Goals table
CREATE TABLE IF NOT EXISTS goals (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    priority REAL DEFAULT 0.5,
    urgency REAL DEFAULT 0.5,
    status TEXT DEFAULT 'active',
    progress REAL DEFAULT 0.0,
    parent_goal_id TEXT,
    tags TEXT DEFAULT '[]',
    deadline TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completion_notes TEXT,
    retry_count INTEGER DEFAULT 0,
    metadata TEXT DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_goals_agent ON goals(agent_id);
CREATE INDEX IF NOT EXISTS idx_goals_status ON goals(status);

-- Reflection logs table
CREATE TABLE IF NOT EXISTS reflection_logs (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    action TEXT NOT NULL,
    outcome TEXT NOT NULL,
    success INTEGER NOT NULL,
    context TEXT DEFAULT '',
    tags TEXT DEFAULT '[]',
    goal_id TEXT,
    created_at TEXT NOT NULL,
    metadata TEXT DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_reflection_agent ON reflection_logs(agent_id);
CREATE INDEX IF NOT EXISTS idx_reflection_success ON reflection_logs(success);

-- Patterns table
CREATE TABLE IF NOT EXISTS patterns (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    pattern_type TEXT NOT NULL,
    description TEXT NOT NULL,
    frequency INTEGER DEFAULT 1,
    first_seen TEXT NOT NULL,
    last_seen TEXT NOT NULL,
    related_tags TEXT DEFAULT '[]',
    suggested_action TEXT
);

-- Proactive insights generated by the daemon
CREATE TABLE IF NOT EXISTS proactive_insights (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    insight TEXT NOT NULL,
    insight_type TEXT NOT NULL,   -- 'pattern' | 'goal_alert' | 'memory_conflict' | 'autonomous_task'
    severity TEXT DEFAULT 'info', -- 'info' | 'warning' | 'critical'
    seen INTEGER DEFAULT 0,       -- 0 = unread, 1 = read by agent
    created_at TEXT NOT NULL,
    source_job TEXT               -- which daemon job generated this
);
CREATE INDEX IF NOT EXISTS idx_insights_agent ON proactive_insights(agent_id);
CREATE INDEX IF NOT EXISTS idx_insights_seen ON proactive_insights(seen);

-- Autonomous tasks generated by the daemon
CREATE TABLE IF NOT EXISTS autonomous_tasks (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    title TEXT NOT NULL,
    reason TEXT NOT NULL,         -- why the daemon created this task
    status TEXT DEFAULT 'pending',-- 'pending' | 'acknowledged' | 'done'
    priority REAL DEFAULT 0.5,
    created_at TEXT NOT NULL,
    source_job TEXT
);
CREATE INDEX IF NOT EXISTS idx_atasks_agent ON autonomous_tasks(agent_id);
CREATE INDEX IF NOT EXISTS idx_atasks_status ON autonomous_tasks(status);

-- Daemon heartbeat — one row per agent_id
CREATE TABLE IF NOT EXISTS daemon_heartbeat (
    agent_id TEXT PRIMARY KEY,
    last_seen TEXT NOT NULL,
    jobs_run INTEGER DEFAULT 0,
    status TEXT DEFAULT 'running'
);
"""


def init_db():
    """Initialize database with schema."""
    import sqlite3
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=5000")
    conn.executescript(SCHEMA_SQL)
    conn.commit()
    # Init graph tables
    from graph.schema import init_graph
    init_graph(conn)
    # Init event bus table
    from events.store import init_event_store
    init_event_store()
    # Init approval queue table
    from approval.queue import init_approval_queue
    init_approval_queue()
    conn.close()


async def get_db():
    """Get async database connection with proper PRAGMAs."""
    db = await aiosqlite.connect(DB_PATH)
    db.row_factory = aiosqlite.Row
    await db.execute("PRAGMA foreign_keys = ON")
    await db.execute("PRAGMA busy_timeout=5000")
    return db


def now_utc() -> str:
    """Return current UTC time as ISO 8601 string."""
    return datetime.now(timezone.utc).isoformat()


def parse_tags(tags_str: str) -> List[str]:
    """Parse JSON tags string to list."""
    try:
        return json.loads(tags_str)
    except:
        return []


def serialize_tags(tags: List[str]) -> str:
    """Serialize tags list to JSON string."""
    return json.dumps(tags)


def row_to_dict(row) -> Dict[str, Any]:
    """Convert a database row to dictionary."""
    if row is None:
        return {}
    return {key: row[key] for key in row.keys()}
